Controllers/LojaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjetoLP3.Models;

namespace ProjetoLP3.Controllers
{
    [OutputCache(Location = System.Web.UI.OutputCacheLocation.None, NoStore = true)]
    public class LojaController : BaseController
    {
        private SeminarioLP3Container db = new SeminarioLP3Container();

        public ActionResult Index()
        {
            var lojas = db.Loja.Include("Rua").ToList();
            return View(lojas);
        }

        public ActionResult Inserir()
        {
            ViewBag.FkRua = new SelectList(db.Rua, "IdRua", "Nome");
            return View();
        }
        [HttpPost]
        public ActionResult Inserir(Loja loja)
        {
            if (ModelState.IsValid)
            {
                db.Loja.Add(loja);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FkRua = new SelectList(db.Rua, "IdRua", "Nome");
            return View(loja);
        }

        public ActionResult Alterar(int id)
        {
            Loja loja = db.Loja.Find(id);
            ViewBag.FkRua = new SelectList(db.Rua, "IdRua", "Nome");
            return View(loja);
        }
        [HttpPost]
        public ActionResult Alterar(Loja loja)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loja).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FkRua = new SelectList(db.Rua, "IdRua", "Nome");
            return View(loja);
        }

        public ActionResult Excluir(int id)
        {
            Loja loja = db.Loja.Find(id);
            ViewBag.FkRua = new SelectList(db.Rua, "IdRua", "Nome");
            return View(loja);
        }
        [HttpPost, ActionName("Excluir")]
        public ActionResult EfetuarExclusao(int id)
        {
            try
            {
                Loja loja = db.Loja.Find(id);
                db.Loja.Remove(loja);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("ErroExcluir");
            }
        }
        public ActionResult ErroExcluir()
        {
            return View();
        }

        public ActionResult Detalhes(int id)
        {
            Loja loja = db.Loja.Find(id);
            ViewBag.FkRua = new SelectList(db.Rua, "IdRua", "Nome");
            if (loja == null)
            {
                return HttpNotFound();
            }
            return View(loja);
        }

        public ActionResult ValidaCPNJ(string cnpj)
        {
            var val = db.Loja.Where(l => l.CNPJ == cnpj).FirstOrDefault();
            
            if (val != null)
                return Json(false, JsonRequestBehavior.AllowGet);
            else 
                return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

Controllers/RuaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjetoLP3.Models;

namespace ProjetoLP3.Controllers
{
    [OutputCache(Location = System.Web.UI.OutputCacheLocation.None, NoStore = true)]
    public class RuaController : BaseController
    {
        private SeminarioLP3Container db = new SeminarioLP3Container();

        public ActionResult Index()
        {
            var ruas = db.Rua.Include("Bairro").Include("TipoComercio").ToList();
            return View(ruas);
        }

        public ActionResult Inserir()
        {
            ViewBag.FkBairro = new SelectList(db.Bairro, "IdBairro", "Nome");
            ViewBag.FkTipoComercio = new SelectList(db.TipoComercio, "IdComercio", "Nome");
            return View();
        }
        [HttpPost]
        public ActionResult Inserir(Rua rua)
        {
            if (ModelState.IsValid)
            {
                db.Rua.Add(rua);
                db.SaveChanges();
                return RedirectToAction("Index");
            }           
            ViewBag.FkBairro = new SelectList(db.Bairro, "IdBairro", "Nome");
            ViewBag.FkTipoComercio = new SelectList(db.TipoComercio, "IdComercio", "Nome");
            return View(rua);
        }

        public ActionResult Alterar(int id)
        {
            Rua rua = db.Rua.Find(id);
            ViewBag.FkBairro = new SelectList(db.Bairro, "IdBairro", "Nome");
            ViewBag.FkTipoComercio = new SelectList(db.TipoComercio, "IdComercio", "Nome");
            return View(rua);
        }
        [HttpPost]
        public ActionResult Alterar(Rua rua)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rua).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FkBairro = new SelectList(db.Bairro, "IdBairro", "Nome");
            ViewBag.FkTipoComercio = new SelectList(db.TipoComercio, "IdComercio", "Nome");
            return View(rua);
        }

        public ActionResult Excluir(int id)
        {
            Rua rua = db.Rua.Find(id);
            ViewBag.FkBairro = new SelectList(db.Bairro, "IdBairro", "Nome");
            ViewBag.FkTipoComercio = new SelectList(db.TipoComercio, "IdComercio", "Nome");
            return View(rua);
        }
        [HttpPost, ActionName("Excluir")]
        public ActionResult EfetuarExclusao(int id)
        {
            try
            {
                Rua rua = db.Rua.Find(id);
                db.Rua.Remove(rua);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("ErroExcluir");
            }
        }
        public ActionResult ErroExcluir()
        {
            return View();
        }

        public ActionResult Detalhes(int id)
        {
            Rua rua = db.Rua.Find(id);
            ViewBag.FkBairro = new SelectList(db.Bairro, "IdBairro", "Nome");
            ViewBag.FkTipoComercio = new SelectList(db.TipoComercio, "IdComercio", "Nome");
            if (rua == null)
            {
                return HttpNotFound();
            }
            return View(rua);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ruas de Comércio</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="@Url.Content("~/Scripts/jquery-3.3.1.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
    <link rel="stylesheet" href="~/StyleSheets/animated-bg.css" />
    <link rel="stylesheet" href="~/StyleSheets/footer.css" />
    <link rel="stylesheet" href="~/StyleSheets/parallax.css" />
    <link rel="stylesheet" href="~/StyleSheets/pesquisa.css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" id="navbar" style="transition: top 0.2s;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ruas de Comércio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Bairros", "Index", "Bairro")</li>
                    <li>@Html.ActionLink("Categorias de Produto", "Index", "CategoriaProduto")</li>
                    <li>@Html.ActionLink("Lojas", "Index", "Loja")</li>
                    <li>@Html.ActionLink("Ruas", "Index", "Rua")</li>
                    <li>@Html.ActionLink("Tipos de Comércio", "Index", "TipoComercio")</li>
                    <li>@Html.ActionLink("Usuários", "Index", "Usuario")</li>
                    <li><a id="botao-sair" class="btn btn-danger" style="display: none; color: white;">Sair</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content opaco" style="padding-bottom:40px;">
        @RenderBody()
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - Ruas de Comércio</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src=" @Url.Content("~/Scripts/Autenticacao.js")"></script>
    <script src=" @Url.Content("~/Scripts/EsconderMenu.js")"></script>
    @RenderSection("scripts", required: false)
</body>
</html>